language: node_js

node_js:
  - '0.10'

before_install: gem install compass

before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'

after_success:
  - coveralls

notifications:
  email:
    - marjori@atados.com.br
